Cut and pasted from estimate_Ã…DT.ipynb (to clean up that file)

# Some cleaning/pre-processing/feature-adding

In [ ]:
overXkmh = trajs_gdf[trajs_gdf.speed > 200].sort_values(by='speed')

In [ ]:
points_gdf.xs(overXkmh[overXkmh.speed == overXkmh.speed.max()].index.values[0], level='trajectory_sid', drop_level=False)

,,x,y,timestamp,geometry
,trajectory_sid,,,,
7730448,6090494,317219.153170,6.384036e+06,2019-08-02 07:22:56+02:00,POINT (317219.153 6384036.459)
7730449,6090494,317059.408116,6.384902e+06,2019-08-02 07:22:58+02:00,POINT (317059.408 6384902.311)
7730450,6090494,317114.145334,6.384925e+06,2019-08-02 07:23:00+02:00,POINT (317114.145 6384924.994)

In [ ]:
overXkmh.describe()

           duration   data_points      distance         speed
count  14029.000000  14029.000000  14029.000000  14029.000000
mean      24.669613      3.454345   1736.091168    260.031380
std       13.954021      1.037850    894.945173     43.743694
min        4.000000      3.000000    246.000000    200.025000
25%       17.000000      3.000000   1314.000000    226.683871
50%       20.000000      3.000000   1501.000000    252.000000
75%       29.000000      4.000000   1936.000000    284.850000
max      290.000000     34.000000  18607.000000    846.000000

In [ ]:
overXkmh[overXkmh.data_points == 34].to_csv('../Data/QGIS/overXkmh_34p.csv', index=False)

In [ ]:
overXkmh[overXkmh.data_points == 34]

,start_time,stop_time,duration,data_points,distance,speed,line
sid,,,,,,,
1387858,2019-10-21 10:29:26+02:00,2019-10-21 10:32:52+02:00,206,34,11588,202.508738,"LINESTRING (314876.163 6411684.178, 314998.934..."

In [ ]:
points_gdf.xs(1387858, level='trajectory_sid').geometry.to_csv('../Data/QGIS/overXkmh_34p_points.csv', index=False)

In [ ]:
traj_1387858_points = points_gdf.xs(1387858, level='trajectory_sid').copy()
traj_1387858_points.head(3)

,x,y,timestamp,geometry
2940012,314876.163016,6.411684e+06,2019-10-21 10:29:26+02:00,POINT (314876.163 6411684.178)
2940013,314998.934078,6.411895e+06,2019-10-21 10:29:31+02:00,POINT (314998.934 6411894.823)
2940014,315148.813481,6.412074e+06,2019-10-21 10:29:36+02:00,POINT (315148.813 6412074.120)

In [ ]:
overXkmh.to_csv('../DATA/QGIS/overXkmh.csv', index=False)

### From `segment_calcs_2.ipynb`

In [ ]:
traj_1387858_points['prev_point'] = traj_1387858_points.geometry.shift(1)
points['prev_trajectory_sid'] = points['trajectory_sid'].shift(1)

In [ ]:
def compute_distance(row):
    if row.name == 0 or row['trajectory_sid'] != row['prev_trajectory_sid']:
        return 0
    t1 = (row['prev_x'], row['prev_y'])
    t2 = (row['x'], row['y'])
    return shp.distance(row.geometry, row.prev_point)

In [ ]:
traj_1387858_points['distance'] = traj_1387858_points.apply(\
    lambda x: shp.distance(x.geometry, x.prev_point), axis=1)

In [ ]:
traj_1387858_points

,x,y,timestamp,geometry,prev_point,distance
2940012,314876.163016,6.411684e+06,2019-10-21 10:29:26+02:00,POINT (314876.163 6411684.178),None,NaN
2940013,314998.934078,6.411895e+06,2019-10-21 10:29:31+02:00,POINT (314998.934 6411894.823),POINT (314876.163 6411684.178),243.811638
2940014,315148.813481,6.412074e+06,2019-10-21 10:29:36+02:00,POINT (315148.813 6412074.120),POINT (314998.934 6411894.823),233.690821
2940015,315340.338095,6.412215e+06,2019-10-21 10:29:41+02:00,POINT (315340.338 6412214.715),POINT (315148.813 6412074.120),237.589119
2940016,315565.770160,6.412304e+06,2019-10-21 10:29:46+02:00,POINT (315565.770 6412303.589),POINT (315340.338 6412214.715),242.318482
2940017,315818.890045,6.412348e+06,2019-10-21 10:29:51+02:00,POINT (315818.890 6412347.724),POINT (315565.770 6412303.589),256.938754
2940018,316082.062276,6.412365e+06,2019-10-21 10:29:56+02:00,POINT (316082.062 6412364.655),POINT (315818.890 6412347.724),263.716324
2940019,316334.764736,6.412361e+06,2019-10-21 10:30:01+02:00,POINT (316334.765 6412360.899),POINT (316082.062 6412364.655),252.730376
2940020,316594.947271,6.412365e+06,2019-10-21 10:30:06+02:00,POINT (316594.947 6412364.621),POINT (316334.765 6412360.899),260.209163
2940021,316854.310708,6.412390e+06,2019-10-21 10:30:11+02:00,POINT (316854.311 6412389.581),POINT (316594.947 6412364.621),260.561682
2940022,317126.203218,6.412428e+06,2019-10-21 10:30:16+02:00,POINT (317126.203 6412428.481),POINT (316854.311 6412389.581),274.661130
2940023,317396.409297,6.412470e+06,2019-10-21 10:30:21+02:00,POINT (317396.409 6412469.706),POINT (317126.203 6412428.481),273.332711
2940024,317672.596549,6.412512e+06,2019-10-21 10:30:26+02:00,POINT (317672.597 6412511.791),POINT (317396.409 6412469.706),279.375357
2940025,317954.977544,6.412573e+06,2019-10-21 10:30:31+02:00,POINT (317954.978 6412572.568),POINT (317672.597 6412511.791),288.847404
2940026,318235.638944,6.412661e+06,2019-10-21 10:30:36+02:00,POINT (318235.639 6412661.314),POINT (317954.978 6412572.568),294.358046
2940027,319052.217664,6.413105e+06,2019-10-21 10:30:51+02:00,POINT (319052.218 6413104.959),POINT (318235.639 6412661.314),929.312656
2940028,319334.737272,6.413276e+06,2019-10-21 10:30:56+02:00,POINT (319334.737 6413276.195),POINT (319052.218 6413104.959),330.361821
2940029,319622.124945,6.413437e+06,2019-10-21 10:31:01+02:00,POINT (319622.125 6413437.196),POINT (319334.737 6413276.195),329.413315
2940030,319911.064983,6.413580e+06,2019-10-21 10:31:06+02:00,POINT (319911.065 6413580.309),POINT (319622.125 6413437.196),322.440241
2940031,320203.295939,6.413718e+06,2019-10-21 10:31:11+02:00,POINT (320203.296 6413717.720),POINT (319911.065 6413580.309),322.925225
2940032,320477.600964,6.413854e+06,2019-10-21 10:31:16+02:00,POINT (320477.601 6413853.723),POINT (320203.296 6413717.720),306.169839
2940033,321331.014902,6.414282e+06,2019-10-21 10:31:32+02:00,POINT (321331.015 6414281.661),POINT (320477.601 6413853.723),954.696920
2940034,321585.113424,6.414406e+06,2019-10-21 10:31:37+02:00,POINT (321585.113 6414406.370),POINT (321331.015 6414281.661),283.052216
2940035,321837.267244,6.414528e+06,2019-10-21 10:31:42+02:00,POINT (321837.267 6414527.837),POINT (321585.113 6414406.370),279.885108
2940036,322094.201814,6.414650e+06,2019-10-21 10:31:47+02:00,POINT (322094.202 6414650.221),POINT (321837.267 6414527.837),284.593236
2940037,322349.884158,6.414772e+06,2019-10-21 10:31:52+02:00,POINT (322349.884 6414771.562),POINT (322094.202 6414650.221),283.014069
2940038,322601.498555,6.414882e+06,2019-10-21 10:31:57+02:00,POINT (322601.499 6414881.949),POINT (322349.884 6414771.562),274.763845
2940039,322852.161420,6.414985e+06,2019-10-21 10:32:02+02:00,POINT (322852.161 6414984.590),POINT (322601.499 6414881.949),270.863343
2940040,323105.086097,6.415085e+06,2019-10-21 10:32:07+02:00,POINT (323105.086 6415084.916),POINT (322852.161 6414984.590),272.095958
2940041,323612.179958,6.415288e+06,2019-10-21 10:32:17+02:00,POINT (323612.180 6415287.788),POINT (323105.086 6415084.916),546.169762
2940042,324120.796602,6.415500e+06,2019-10-21 10:32:27+02:00,POINT (324120.797 6415499.573),POINT (323612.180 6415287.788),550.948029
2940043,324374.986452,6.415603e+06,2019-10-21 10:32:32+02:00,POINT (324374.986 6415603.264),POINT (324120.797 6415499.573),274.525579
2940044,324634.453047,6.415706e+06,2019-10-21 10:32:37+02:00,POINT (324634.453 6415705.625),POINT (324374.986 6415603.264),278.927686
2940045,325418.084011,6.415985e+06,2019-10-21 10:32:52+02:00,POINT (325418.084 6415984.706),POINT (324634.453 6415705.625),831.843606

In [ ]:
column_names = ['seg_distance', 'seg_duration_s']
first_row = [0, 0]


traj_1387858_points['distance'] = traj_1387858_points.geometry.